name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkou

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip openjdk-17-jdk
          pip3 install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses:  actions/upload-artifact@v4
        with:
          name: royalranks.apk
          path: ./bin/*.apk
